languages:
   JavaScript: true
   Python: true
engines:
  pep8:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.py"
exclude_paths:
- "**/plugins/**/*"
