language: python
python:
  - "2.7"
# command to install dependencies
install: 
 - pip install -t lib -r requirements.txt
# command to run tests
script: 
 - python test.py
notifications:
  email: false