language: python
python:
  - "2.7"
  
before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.23.zip -nv
- unzip -q google_appengine_1.9.23.zip
- sudo ln -s `pwd`/google_appengine /usr/local/google_appengine
- sudo ln -s `pwd`/google_appengine/dev_appserver.py /usr/local/bin/dev_appserver.py

# command to install dependencies
install: 
 - pip install -t lib -r requirements.txt
 - pip install WebTest
 - pip install coveralls
 - pip install Pillow
 # - /usr/local/google_appengine/appcfg.py -A salomax-marketplace update .

script:
 - coverage run --source=app openmarketplace_test.py

after_success:
    coveralls

notifications:
  email: false
