application: livremarketplace
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler: Must be /_ah/spi. Apps send requests to /_ah/api, but these are handled at /_ah/spi!!
- url: /_ah/spi/.*
  script: livremarketplace_api.APPLICATION
  secure: always

# The following three handlers route requests to static resources: JS, CSS,
# and HTML.
- url: /js
  static_dir: static/js
- url: /bundle
  static_dir: static/bundle
- url: /css
  static_dir: static/css  
- url: /img
  static_dir: static/img  
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always  
- url: /main
  static_files: static/app/main.html
  upload: static/app/main\.html
  secure: always
- url: /purchase
  static_dir: static/app/purchase
- url: /product
  secure: always
  static_dir: static/app/product
- url: /supplier
  static_dir: static/app/supplier
  secure: always
- url: /customer
  static_dir: static/app/customer
  secure: always
- url: /sale
  static_dir: static/app/sale
  secure: always
- url: /dashboard
  static_dir: static/app/dashboard
  secure: always
- url: /postal
  static_dir: static/app/postal
  secure: always

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: latest            

env_variables:
  WEB_CLIENT_ID: '768767255656-cs88prcq2s6olvb4dhsjdf2r7br50uej.apps.googleusercontent.com'